### PR TITLE
query as hash

### PR DESCRIPTION
**Pull request by draffo-dc**
## Summary

Query params doesn't have to be fixed in the endpoint anymore

### CODE REVIEW

**Comment by icoluccio** [comment]
Is this PR still valid after @alebian's refactor?

**Comment by Enanodr** [comment]
@alebian's PR in not merged yet, and he made a new class. It shouldn't conflict with this PR.
If both approbed, we should replicate this functionality in both classes

**Comment by mishuagopian** [comment]
@Enanodr he's removed the conflicting file. Maybe we can update this PR after that one gets merged.

**Comment by mishuagopian** [comment]
@Enanodr you can update this now!

**Comment by mishuagopian** [comment]
This PR is not valid anymore

**Pull request closed without merging**
