### PR TITLE
Fix typo on install generator spec

### LINKED ISSUE #28: Fix typo on generator spec
On lines 15 and 17, it says requets instead of requests.
File: https://github.com/Wolox/wor-requests/blob/master/spec/wor/generators/install_generator_spec.rb

### PR DESCRIPTION
**Pull request by lmasello**
Resolves #28

### CODE REVIEW

**Review by hdf1996 — APPROVED** [review]

**Review by hdf1996 — CHANGES_REQUESTED** [review]
Oh... it's broken....

**Comment by hdf1986** [comment]
@lmasello You'll need to replace the do/end with {} U_U

**Comment by lmasello** [comment]
@hdf1986 But it would break rubocop. The same's happening on master branch mmm

**Comment by lmasello** [comment]
@hdf1986 Please check the service generator spec diff. It's weird that before it was passing ok.

**Review by hdf1996 — APPROVED** [review]

**Pull request merged**
